backend/config/routes.rb
Rails.application.routes.draw do
  resources :polls

end

backend/app/models/party.rb
class Party < ActiveRecord::Base
	has_many :results
end

backend/app/models/poll.rb
class Poll < ActiveRecord::Base
	has_many :results
	accepts_nested_attributes_for :results
end

backend/app/models/result.rb
class Result < ActiveRecord::Base
	belongs_to :poll
	belongs_to :party
end

backend/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :allow_cors

	def allow_cors
	  headers["Access-Control-Allow-Origin"] = "*"
	  headers["Access-Control-Allow-Methods"] = %w{GET POST PUT DELETE}.join(",")
	  headers["Access-Control-Allow-Headers"] =
	    %w{Origin Accept Content-Type X-Requested-With X-CSRF-Token}.join(",")

	  head(:ok) if request.request_method == "OPTIONS"
	  # or, render text: ''
	  # if that's more your style
	end
end

backend/app/controllers/polls_controller.rb
class PollsController < ApplicationController
  before_action :set_poll, only: [:show, :edit, :update, :destroy]

  # GET /polls
  # GET /polls.json
  def index
    @polls = Poll.all
    render :json => @polls.as_json(:include => :results)
  end

  # GET /polls/1
  # GET /polls/1.json
  def show
  end

  # GET /polls/new
  def new
    @poll = Poll.new
    Party.all.each do |party|
      @poll.results.build(party: party)
    end
  end

  # GET /polls/1/edit
  def edit
  end

  # POST /polls
  # POST /polls.json
  def create
    debugger
    @poll = Poll.new(poll_params)

    respond_to do |format|
      if @poll.save
        format.html { redirect_to @poll, notice: 'Poll was successfully created.' }
        format.json { render :show, status: :created, location: @poll }
      else
        format.html { render :new }
        format.json { render json: @poll.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /polls/1
  # PATCH/PUT /polls/1.json
  def update
    respond_to do |format|
      if @poll.update(poll_params)
        format.html { redirect_to @poll, notice: 'Poll was successfully updated.' }
        format.json { render :show, status: :ok, location: @poll }
      else
        format.html { render :edit }
        format.json { render json: @poll.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /polls/1
  # DELETE /polls/1.json
  def destroy
    @poll.destroy
    respond_to do |format|
      format.html { redirect_to polls_url, notice: 'Poll was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_poll
      @poll = Poll.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def poll_params
      params.require(:poll).permit(:source, :poller, :date, :population,  results_attributes: [:id,:party_id,:mandates] )
    end
end

backend/app/helpers/application_helper.rb
module ApplicationHelper
end

backend/app/helpers/polls_helper.rb
module PollsHelper
end

backend/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ElectionPolls</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

backend/app/views/polls/_form.html.haml
= simple_form_for(@poll) do |f|
  = f.error_notification

  .form-inputs
    = f.input :source
    = f.input :poller
    = f.input :date
    = f.input :population
    = f.simple_fields_for :results do |f_results|
      = f_results.association :party
      = f_results.input :mandates

  .form-actions
    = f.button :submit

backend/app/views/polls/edit.html.haml
%h1 Editing poll

= render 'form'

= link_to 'Show', @poll
\|
= link_to 'Back', polls_path

backend/app/views/polls/index.html.haml
%h1 Listing polls

%table
  %thead
    %tr
      %th Source
      %th Poller
      %th Date
      %th Population
      %th
      %th
      %th
      
  %tbody
    - @polls.each do |poll|
      %tr
        %td= poll.source
        %td= poll.poller
        %td= poll.date
        %td= poll.population
        %td= link_to 'Show', poll
        %td= link_to 'Edit', edit_poll_path(poll)
        %td= link_to 'Destroy', poll, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Poll', new_poll_path

backend/app/views/polls/new.html.haml
%h1 New poll

= render 'form'

= link_to 'Back', polls_path

backend/app/views/polls/show.html.haml
%p#notice= notice

%p
  %b Source:
  = @poll.source
%p
  %b Poller:
  = @poll.poller
%p
  %b Date:
  = @poll.date
%p
  %b Population:
  = @poll.population

= link_to 'Edit', edit_poll_path(@poll)
\|
= link_to 'Back', polls_path